# Generated by Django 5.0.6 on 2024-06-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('addition', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemValueGrossPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLifecycleInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_change_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('product_title', models.CharField(max_length=255)),
                ('article_number', models.CharField(max_length=50)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_order_id', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
                ('links', models.JSONField()),
                ('delivery_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_address', to='otto.address')),
                ('invoice_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_invoice_address', to='otto.address')),
                ('order_lifecycle_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otto.orderlifecycleinformation')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otto.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PositionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_item_id', models.CharField(max_length=50)),
                ('fulfillment_status', models.CharField(max_length=50)),
                ('expected_delivery_date', models.DateTimeField()),
                ('cancellation_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('item_value_gross_price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otto.itemvaluegrossprice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otto.product')),
            ],
        ),
        migrations.CreateModel(
            name='InitialDeliveryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_fee_amount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otto.itemvaluegrossprice')),
                ('position_item_ids', models.ManyToManyField(to='otto.positionitem')),
            ],
        ),
    ]
