# Generated by Django 5.0.6 on 2024-06-26 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('sales_order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=100, unique=True)),
                ('product_title', models.CharField(max_length=255)),
                ('article_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingInfo',
            fields=[
                ('carrier', models.CharField(max_length=20)),
                ('tracking_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemValueGrossPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('amount', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='PositionItem',
            fields=[
                ('position_item_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fulfillment_status', models.CharField(max_length=100)),
                ('sentDate', models.DateTimeField()),
                ('item_value_gross_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otto.itemvaluegrossprice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otto.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otto.product')),
                ('tracking_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otto.trackinginfo')),
            ],
        ),
    ]
