# Generated by Django 5.0.6 on 2024-06-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_method', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('product_title', models.CharField(max_length=255)),
                ('article_number', models.CharField(max_length=100)),
                ('ean', models.CharField(max_length=100)),
                ('vat_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryFeeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('amount', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='InitialDeliveryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vat_rate', models.FloatField()),
                ('delivery_fee_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otto.deliveryfeeamount')),
            ],
        ),
        migrations.CreateModel(
            name='ItemValueGrossPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('amount', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='PositionItem',
            fields=[
                ('position_item_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('fulfillment_status', models.CharField(max_length=100)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('item_value_gross_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otto.itemvaluegrossprice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_items', to='otto.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('sales_order_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
                ('lifecycle_change_date', models.DateTimeField(blank=True, null=True)),
                ('initial_delivery_fees', models.ManyToManyField(related_name='orders', to='otto.initialdeliveryfee')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otto.payment')),
                ('position_items', models.ManyToManyField(related_name='orders', to='otto.positionitem')),
            ],
        ),
        migrations.AddField(
            model_name='initialdeliveryfee',
            name='position_items',
            field=models.ManyToManyField(related_name='delivery_fees', to='otto.positionitem'),
        ),
        migrations.CreateModel(
            name='ProductDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('type', 'display_name', 'value')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.ManyToManyField(blank=True, related_name='products', to='otto.productdimension'),
        ),
        migrations.AlterUniqueTogether(
            name='initialdeliveryfee',
            unique_together={('name', 'vat_rate')},
        ),
    ]
