# Generated by Django 5.0.6 on 2024-06-25 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addition',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='salutation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='initialdeliveryfee',
            name='delivery_fee_amount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otto.itemvaluegrossprice'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_lifecycle_information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otto.orderlifecycleinformation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otto.payment'),
        ),
        migrations.AlterField(
            model_name='positionitem',
            name='expected_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='positionitem',
            name='item_value_gross_price',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='otto.itemvaluegrossprice'),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('shipment_id', models.CharField(max_length=20)),
                ('carrier', models.CharField(max_length=50)),
                ('tracking_number', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
                ('occurred_on', models.DateTimeField()),
                ('ship_from_adress', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_from_adress', to='otto.address')),
            ],
        ),
    ]
